// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI-m-dkTHuj6rVwxIu4IAp1k9GiI8Y5uE',
    appId: '1:202245564888:web:7b9cce54a84ac199bc6aad',
    messagingSenderId: '202245564888',
    projectId: 'voicecloning-4f183',
    authDomain: 'voicecloning-4f183.firebaseapp.com',
    storageBucket: 'voicecloning-4f183.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0d-D8SMDn6opWcmQ-KARYodgnswxQlMw',
    appId: '1:202245564888:android:f41756eb3507d85bbc6aad',
    messagingSenderId: '202245564888',
    projectId: 'voicecloning-4f183',
    storageBucket: 'voicecloning-4f183.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAjq1kTsPnHf5HT6Q_DSh2AEu3yyfiB9A',
    appId: '1:202245564888:ios:958eeb52d022881abc6aad',
    messagingSenderId: '202245564888',
    projectId: 'voicecloning-4f183',
    storageBucket: 'voicecloning-4f183.firebasestorage.app',
    iosBundleId: 'com.example.voicecloning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAjq1kTsPnHf5HT6Q_DSh2AEu3yyfiB9A',
    appId: '1:202245564888:ios:958eeb52d022881abc6aad',
    messagingSenderId: '202245564888',
    projectId: 'voicecloning-4f183',
    storageBucket: 'voicecloning-4f183.firebasestorage.app',
    iosBundleId: 'com.example.voicecloning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI-m-dkTHuj6rVwxIu4IAp1k9GiI8Y5uE',
    appId: '1:202245564888:web:8582f00f6057afe7bc6aad',
    messagingSenderId: '202245564888',
    projectId: 'voicecloning-4f183',
    authDomain: 'voicecloning-4f183.firebaseapp.com',
    storageBucket: 'voicecloning-4f183.firebasestorage.app',
  );
}
